name: "Sample react CI Pipeline / Workflow"

on:
    push:
        branches:
            - main
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
<<<<<<< HEAD
            - name: "Setup Node JS"
              uses: actions/setup-node@v4
=======
            - name : "Setup Node JS"
              uses: actions/setup-node@v2
>>>>>>> 840ad671dbd4e72cb35ef74fc1ff26ea26c83c4f
              with:
                node-version: '14'
